# Generated by Django 3.2.18 on 2023-11-14 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='COURSE',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='sem',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
